version: '3'

services:
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/code
    command: bash -c "python manage.py runserver 0.0.0.0:8000"